CREATE TABLE IF NOT EXISTS lojas (
    id INTEGER PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(30) NULL,
    endereco VARCHAR(200) NULL,
    cor_primaria VARCHAR(7) NOT NULL DEFAULT '#0e7490',
    cor_secundaria_fonte VARCHAR(7) NOT NULL DEFAULT '#5f6f82',
    logo_url TEXT NULL,
    usuario_admin_id INTEGER NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'cliente',
    loja_id INTEGER NULL,
    telefone VARCHAR(30) NULL,
    endereco VARCHAR(200) NULL,
    cidade VARCHAR(80) NULL,
    estado VARCHAR(40) NULL,
    cep VARCHAR(20) NULL,
    complemento VARCHAR(120) NULL,
    CONSTRAINT fk_usuarios_loja FOREIGN KEY (loja_id) REFERENCES lojas(id)
);

CREATE TABLE IF NOT EXISTS produtos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    preco NUMERIC(10,2),
    loja_id INTEGER NULL,
    CONSTRAINT fk_produtos_loja FOREIGN KEY (loja_id) REFERENCES lojas(id)
);

CREATE TABLE IF NOT EXISTS horarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER,
    produto_id INTEGER,
    loja_id INTEGER,
    data_hora TIMESTAMP,
    CONSTRAINT fk_horarios_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_horarios_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
    CONSTRAINT fk_horarios_loja FOREIGN KEY (loja_id) REFERENCES lojas(id)
);