using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Update;
using Microsoft.IdentityModel.Tokens;
using Npgsql;
using back_end.Data;

var builder = WebApplication.CreateBuilder(args);

var renderPort = Environment.GetEnvironmentVariable("PORT");
var aspnetcoreUrls = Environment.GetEnvironmentVariable("ASPNETCORE_URLS");
if (!string.IsNullOrWhiteSpace(renderPort))
{
    builder.WebHost.UseUrls($"http://0.0.0.0:{renderPort}");
}
else if (string.IsNullOrWhiteSpace(aspnetcoreUrls))
{
    builder.WebHost.UseUrls("http://0.0.0.0:5000");
}

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddProblemDetails();

const string CorsPolicyName = "AllowAll";
builder.Services.AddCors(options =>
{
    options.AddPolicy(CorsPolicyName, policy =>
    {
        policy
            .AllowAnyOrigin()
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

var jwtKey = builder.Configuration["Jwt:Key"] ?? "change_this_secret_in_production";
var jwtIssuer = builder.Configuration["Jwt:Issuer"] ?? "appointment-booking-system";
var jwtAudience = builder.Configuration["Jwt:Audience"] ?? "appointment-booking-system";

var connectionString =
    builder.Configuration.GetConnectionString("DefaultConnection")
    ?? Environment.GetEnvironmentVariable("ConnectionStrings__DefaultConnection")
    ?? "Host=localhost;Port=5432;Username=postgres;Password=postgres;Database=booking_system;SSL Mode=Disable;Trust Server Certificate=true";

builder.Services.AddDbContext<BookingContext>(options =>
    options.UseNpgsql(
        connectionString,
        npgsql => npgsql.EnableRetryOnFailure(5, TimeSpan.FromSeconds(10), null)));

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.RequireHttpsMetadata = false;
    options.SaveToken = true;
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = jwtIssuer,
        ValidAudience = jwtAudience,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey))
    };
});

builder.Services.AddAuthorization();

var app = builder.Build();

app.UseExceptionHandler(errorApp =>
{
    errorApp.Run(async context =>
    {
        var exceptionFeature = context.Features.Get<IExceptionHandlerFeature>();
        var exception = exceptionFeature?.Error;

        context.Response.StatusCode = StatusCodes.Status500InternalServerError;
        context.Response.ContentType = "application/json";

        var message = "Ocorreu um erro interno no servidor.";

        if (exception is DbUpdateException dbUpdateException && TryGetPostgresException(dbUpdateException, out _))
        {
            message = "Falha ao salvar dados no banco de dados. Verifique se as tabelas foram criadas no Supabase.";
        }
        else if (exception is NpgsqlException)
        {
            message = "Falha ao acessar o banco de dados. Tente novamente em instantes.";
        }
        else if (exception is InvalidOperationException)
        {
            message = "Falha de configuracao interna da aplicacao.";
        }

        await context.Response.WriteAsJsonAsync(new
        {
            message,
            traceId = context.TraceIdentifier
        });
    });
});

app.UseSwagger();
app.UseSwaggerUI();

app.UseHttpsRedirection();

app.UseCors(CorsPolicyName);
app.UseAuthentication();
app.UseAuthorization();

var shouldInitializeDatabase =
    !app.Environment.IsProduction()
    || string.Equals(
        Environment.GetEnvironmentVariable("RUN_DB_INIT"),
        "true",
        StringComparison.OrdinalIgnoreCase);

if (shouldInitializeDatabase)
{
    try
    {
        using var scope = app.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<BookingContext>();

        db.Database.ExecuteSqlRaw(@"
        CREATE TABLE IF NOT EXISTS lojas (
            id INTEGER PRIMARY KEY,
            nome VARCHAR(100) NOT NULL,
            telefone VARCHAR(30) NULL,
            endereco VARCHAR(200) NULL,
            cor_primaria VARCHAR(7) NOT NULL DEFAULT '#0e7490',
            cor_secundaria_fonte VARCHAR(7) NOT NULL DEFAULT '#5f6f82',
            logo_url TEXT NULL,
            usuario_admin_id INTEGER NULL
        );

        CREATE TABLE IF NOT EXISTS usuarios (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome VARCHAR(100) NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL,
            senha_hash VARCHAR(255) NOT NULL,
            role VARCHAR(20) NOT NULL DEFAULT 'cliente',
            loja_id INTEGER NULL,
            telefone VARCHAR(30) NULL,
            endereco VARCHAR(200) NULL,
            cidade VARCHAR(80) NULL,
            estado VARCHAR(40) NULL,
            cep VARCHAR(20) NULL,
            complemento VARCHAR(120) NULL,
            CONSTRAINT fk_usuarios_loja FOREIGN KEY (loja_id) REFERENCES lojas(id)
        );

        CREATE TABLE IF NOT EXISTS produtos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome VARCHAR(100) NOT NULL,
            preco NUMERIC(10,2),
            loja_id INTEGER NULL,
            CONSTRAINT fk_produtos_loja FOREIGN KEY (loja_id) REFERENCES lojas(id)
        );

        CREATE TABLE IF NOT EXISTS horarios (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            usuario_id INTEGER,
            produto_id INTEGER,
            loja_id INTEGER,
            data_hora TIMESTAMP,
            CONSTRAINT fk_horarios_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
            CONSTRAINT fk_horarios_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
            CONSTRAINT fk_horarios_loja FOREIGN KEY (loja_id) REFERENCES lojas(id)
        )");

        ExecuteSqlIgnoringKnownErrors(db, "ALTER TABLE lojas ADD COLUMN IF NOT EXISTS cor_secundaria_fonte VARCHAR(7) NOT NULL DEFAULT '#5f6f82'");
        ExecuteSqlIgnoringKnownErrors(db, "ALTER TABLE lojas ADD COLUMN IF NOT EXISTS logo_url TEXT NULL");
        ExecuteSqlIgnoringKnownErrors(db, "ALTER TABLE lojas ALTER COLUMN logo_url TYPE TEXT");
        ExecuteSqlIgnoringKnownErrors(db, "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS loja_id INTEGER NULL");
        ExecuteSqlIgnoringKnownErrors(db, "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS telefone VARCHAR(30) NULL");
        ExecuteSqlIgnoringKnownErrors(db, "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS endereco VARCHAR(200) NULL");
        ExecuteSqlIgnoringKnownErrors(db, "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS cidade VARCHAR(80) NULL");
        ExecuteSqlIgnoringKnownErrors(db, "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS estado VARCHAR(40) NULL");
        ExecuteSqlIgnoringKnownErrors(db, "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS cep VARCHAR(20) NULL");
        ExecuteSqlIgnoringKnownErrors(db, "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS complemento VARCHAR(120) NULL");
        ExecuteSqlIgnoringKnownErrors(db, "ALTER TABLE produtos ADD COLUMN IF NOT EXISTS loja_id INTEGER NULL");
        ExecuteSqlIgnoringKnownErrors(db, "ALTER TABLE horarios ADD COLUMN IF NOT EXISTS loja_id INTEGER NULL");

        ExecuteSqlIgnoringKnownErrors(db, "UPDATE usuarios SET loja_id = id WHERE role = 'loja' AND (loja_id IS NULL OR loja_id = 0)");

        ExecuteSqlIgnoringKnownErrors(db, @"
        INSERT INTO lojas (id, nome, cor_primaria, usuario_admin_id)
        SELECT u.id, COALESCE(NULLIF(u.nome, ''), 'BookingApp'), '#0e7490', u.id
        FROM usuarios u
        LEFT JOIN lojas l ON l.id = u.loja_id
        WHERE u.role = 'loja' AND u.loja_id IS NOT NULL AND l.id IS NULL");
    }
    catch (Exception ex)
    {
        app.Logger.LogWarning(ex, "Falha ao inicializar schema do banco. API continuara em execucao.");
    }
}

app.MapControllers();

app.Run();

static void ExecuteSqlIgnoringKnownErrors(BookingContext db, string sql)
{
    try
    {
        db.Database.ExecuteSqlRaw(sql);
    }
    catch (PostgresException ex) when (
        ex.MessageText.Contains("already exists", StringComparison.OrdinalIgnoreCase)
        || ex.Message.Contains("already exists", StringComparison.OrdinalIgnoreCase)
        || ex.Message.Contains("does not exist", StringComparison.OrdinalIgnoreCase)
        || ex.Message.Contains("column", StringComparison.OrdinalIgnoreCase))
    {
        // Idempotent bootstrap: ignore schema drift errors already covered by previous runs.
    }
}

static bool TryGetPostgresException(DbUpdateException exception, out PostgresException? postgresException)
{
    postgresException = exception.InnerException as PostgresException;

    if (postgresException != null)
    {
        return true;
    }

    if (exception.InnerException is not null)
    {
        postgresException = exception.InnerException.InnerException as PostgresException;
        return postgresException != null;
    }

    return false;
}
